"""Добавить колонку end_time

Revision ID: 51ecafa7927d
Revises: 640027d9347a
Create Date: 2024-09-25 11:08:25.104486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ecafa7927d'
down_revision: Union[str, None] = '640027d9347a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('end_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_time')
    # ### end Alembic commands ###
