"""Migration #2

Revision ID: 5daec160e383
Revises: feedaacb3592
Create Date: 2024-09-27 20:55:42.308127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5daec160e383'
down_revision: Union[str, None] = 'feedaacb3592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_time')
    # ### end Alembic commands ###
